title:            Visual Thinking Design Patterns
description:      VTDP Reference
url:              http://visualthinkingdesign.com

links:
  - name:         About
    url:          /about.html
  - name:        Contact
    url:          /author.html

permalink:        /:categories/:title/
markdown:         kramdown

# Local serving settings
host: localhost
port: 4000
