title:            Visual Thinking Design Patterns
description:      VTDP Reference
url:              http://visualthinkingdesign.com
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )

links:
  - name:         About 
    url:          /about.html
  - name:        Contact
    url:          /author.html

permalink:        /:categories/:title/
markdown:         kramdown

# Local serving settings
host: localhost
port: 4000
